# Jekyll config

# Site settings
title: Single Site Style guide
description: Single-site Style guide
baseurl: ""
url: "http://single-site-styleguide.heroku.com"

# Build settings
source: ./styleguide
markdown: kramdown
sass:
  load_paths:
    - ./styles
