# Contentful
contentful:
  spaces:
    - design-system-content:
        space:        $CONTENTFUL_SPACE_ID
        access_token: $CONTENTFUL_DELIVERY_TOKEN
        environment:  master
        all_entries: true
        base_path: ./src
