# Welcome to Jekyll!

# Site settings
title: Single Site Styleguide
email: fred.marecesche@co-operative.coop
description: Single-site Style guide
baseurl: ""
url: "http://heroku.com"

# Build settings
source: _source
markdown: kramdown
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
