title: Card image
label: Card image
status: ready
preview: '@preview-bg'
display:
  min-height: 650px
  max-width: 750px
context:
  heading3:
    text: We’re celebrating LGBT history month
  paragraph:
    text: We’re also asking all Co-op colleagues which Pride events they’d like to get involved in.
