# Jekyll config

# Site settings
title: Single Site Style guide
description: Single-site Style guide
baseurl: ""
url: "http://single-site-styleguide.heroku.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
