# Jekyll config

# Site settings
title: Co-op Design Manual
description: Co-op Design Manual
baseurl: ""
url: "http://coop-design-manual.herokuapp.com"

# Build settings
source: ./
destination: ../build
keep_files: ['css', 'js', 'assets']
markdown: kramdown
